<?php if($this->canShowPaymentChanged()): ?>

    <script type="text/javascript">
        fbq('track', 'AddPaymentInfo', {
            value: <?php echo $this->getQuotePrice() ?>,
            currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>",
            content_name: 'Checkout',
            content_ids: <?php echo json_encode($this->getItemSkus()) ?>
        });
    </script>

<?php endif; ?>