<?php if($this->showAddToCart()): ?>

    <script type="text/javascript">
            fbq('track', 'AddToCart', {
                content_name: "<?php echo $this->getProductName(); ?>",
                content_ids: "<?php echo $this->getProductSku(); ?>",
                content_type: 'product',
                value: <?php echo $this->getProductPrice(); ?>,
                currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>"
            });
    </script>

<?php endif; ?>