<?php if($this->canShowCheckout()): ?>

    <script type="text/javascript">

        fbq('track', 'InitiateCheckout', {
            value: <?php echo $this->getQuotePrice(); ?>,
            currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>",
            content_name: 'Checkout',
            content_ids: <?php echo json_encode($this->getItemSkus()) ?>,
            num_items: <?php echo $this->getItemCount(); ?>
        });

    </script>

<?php endif; ?>