<?php if($this->canShowCheckout()): ?>

    <?php if($this->getItemCount() > 1): ?>
        <script type="text/javascript">

            fbq('track', 'InitiateCheckout', {
                value: <?php echo $this->getQuotePrice(); ?>,
                currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>",
                content_name: 'Checkout',
                content_type: 'product',
                content_ids: <?php echo json_encode($this->getItemSkus()) ?>,
                num_items: <?php echo $this->getItemCount(); ?>
            });

        </script>
    <?php else: ?>
        <script type="text/javascript">

            fbq('track', 'InitiateCheckout', {
                value: <?php echo $this->getQuotePrice(); ?>,
                currency: "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>",
                content_name: 'Checkout',
                content_type: 'product',
                content_ids: "<?php echo $this->getItemSkus() ?>",
                num_items: <?php echo $this->getItemCount(); ?>
            });

        </script>
    <?php endif; ?>

<?php endif; ?>